[package]
name = "autoquant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linregress = "0.5.0"
plotters = "0.3.4"
rand = "0.8.5"
statrs = "0.16.0"
